[package]
name = "osv"
version = "0.1.2"
edition = "2021"
authors = ["Grant Murphy <gcmurphy@pm.me>"]
repository = "https://github.com/gcmurphy/osv"
documentation = "https://docs.rs/osv" 
description = "Rust client library for the osv API"
readme = "README.md"
license = "Apache-2.0"
keywords = ["vulnerabilities", "security", "osv"]


[dependencies]
async-std = { version = "1.12.0", features = ["attributes"]}
chrono = { version = "0.4", features = ["serde"] }
serde = "1.0"
serde_json = "1.0"
surf = "2.3.2"
thiserror = "1.0"
url = "2.3.1"

[dev-dependencies]
comfy-table = "5.0.1"
textwrap = { version = "0.15.0", features = ["default", "terminal_size"] }
