name: Static Analysis - Semgrep
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '30 17 * * 5'

permissions: read-all
jobs:
  semgrep:
    name: Static analysis (semgrep)
    continue-on-error: true
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    permissions:
      actions: read
      contents: read
      security-events: write
    if: (github.action != 'dependabot[bot]')
    steps:
      - name: Semgrep Scan
        uses: actions/checkout@v3
        run: semgrep ci --sarif semgrep-results.sarif
        env:
          SEMGREP_RULES: >-
            p/security-audit
            p/secrets
            p/supply-chain
            p/rust

      - name: Upload results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep-results.sarif
