name: Static Analysis - Semgrep
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '30 17 * * 5'

permissions: read-all
jobs:
  semgrep:
    name: Static analysis (semgrep)
    continue-on-error: true
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    if: (github.action != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v3
      - run: semgrep ci
        env:
          SEMGREP_RULES: >-
            p/security-audit
            p/secrets
            p/supply-chain
            p/rust
